/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomType = IDL.Variant({
  'solo' : IDL.Null,
  'sharedRoom' : IDL.Null,
});
export const Physician = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Pharmacy = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Insurance = IDL.Record({
  'id' : IDL.Nat,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'policyNumber' : IDL.Text,
});
export const ResponsiblePerson = IDL.Record({
  'id' : IDL.Nat,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const MedicationStatus = IDL.Variant({
  'active' : IDL.Null,
  'discontinued' : IDL.Null,
});
export const AdministrationRoute = IDL.Variant({
  'injection' : IDL.Null,
  'inhaled' : IDL.Null,
  'oral' : IDL.Null,
  'intramuscular' : IDL.Null,
  'ophthalmic' : IDL.Null,
  'transdermal' : IDL.Null,
  'sublingual' : IDL.Null,
  'intravenous' : IDL.Null,
  'topical' : IDL.Null,
  'subcutaneous' : IDL.Null,
  'rectal' : IDL.Null,
});
export const Medication = IDL.Record({
  'id' : IDL.Nat,
  'status' : MedicationStatus,
  'dosage' : IDL.Text,
  'prescribingPhysician' : IDL.Opt(Physician),
  'name' : IDL.Text,
  'administrationRoute' : AdministrationRoute,
  'administrationTimes' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'dosageQuantity' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfileWithRole = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const ProfileSetupError = IDL.Variant({ 'NotFound' : IDL.Null });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResidentAccessControl' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        RoomType,
        IDL.Opt(IDL.Text),
        IDL.Vec(Physician),
        IDL.Opt(Pharmacy),
        IDL.Opt(Insurance),
        IDL.Text,
        IDL.Text,
        IDL.Vec(ResponsiblePerson),
        IDL.Vec(Medication),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'ensureRegisteredUser' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfileWithRole' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : UserProfileWithRole, 'err' : ProfileSetupError })],
      ['query'],
    ),
  'healthCheck' : IDL.Func(
      [],
      [IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Opt(IDL.Int) })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomType = IDL.Variant({ 'solo' : IDL.Null, 'sharedRoom' : IDL.Null });
  const Physician = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Pharmacy = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Insurance = IDL.Record({
    'id' : IDL.Nat,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'policyNumber' : IDL.Text,
  });
  const ResponsiblePerson = IDL.Record({
    'id' : IDL.Nat,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const MedicationStatus = IDL.Variant({
    'active' : IDL.Null,
    'discontinued' : IDL.Null,
  });
  const AdministrationRoute = IDL.Variant({
    'injection' : IDL.Null,
    'inhaled' : IDL.Null,
    'oral' : IDL.Null,
    'intramuscular' : IDL.Null,
    'ophthalmic' : IDL.Null,
    'transdermal' : IDL.Null,
    'sublingual' : IDL.Null,
    'intravenous' : IDL.Null,
    'topical' : IDL.Null,
    'subcutaneous' : IDL.Null,
    'rectal' : IDL.Null,
  });
  const Medication = IDL.Record({
    'id' : IDL.Nat,
    'status' : MedicationStatus,
    'dosage' : IDL.Text,
    'prescribingPhysician' : IDL.Opt(Physician),
    'name' : IDL.Text,
    'administrationRoute' : AdministrationRoute,
    'administrationTimes' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'dosageQuantity' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfileWithRole = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const ProfileSetupError = IDL.Variant({ 'NotFound' : IDL.Null });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResidentAccessControl' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          RoomType,
          IDL.Opt(IDL.Text),
          IDL.Vec(Physician),
          IDL.Opt(Pharmacy),
          IDL.Opt(Insurance),
          IDL.Text,
          IDL.Text,
          IDL.Vec(ResponsiblePerson),
          IDL.Vec(Medication),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'ensureRegisteredUser' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfileWithRole' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Variant({
            'ok' : UserProfileWithRole,
            'err' : ProfileSetupError,
          }),
        ],
        ['query'],
      ),
    'healthCheck' : IDL.Func(
        [],
        [IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Opt(IDL.Int) })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };