/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdministrationRoute = { 'injection' : null } |
  { 'inhaled' : null } |
  { 'oral' : null } |
  { 'intramuscular' : null } |
  { 'ophthalmic' : null } |
  { 'transdermal' : null } |
  { 'sublingual' : null } |
  { 'intravenous' : null } |
  { 'topical' : null } |
  { 'subcutaneous' : null } |
  { 'rectal' : null };
export interface Insurance {
  'id' : bigint,
  'address' : string,
  'companyName' : string,
  'contactNumber' : string,
  'policyNumber' : string,
}
export interface Medication {
  'id' : bigint,
  'status' : MedicationStatus,
  'dosage' : string,
  'prescribingPhysician' : [] | [Physician],
  'name' : string,
  'administrationRoute' : AdministrationRoute,
  'administrationTimes' : Array<string>,
  'notes' : string,
  'dosageQuantity' : string,
}
export type MedicationStatus = { 'active' : null } |
  { 'discontinued' : null };
export interface Pharmacy {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'contactNumber' : string,
}
export interface Physician {
  'id' : bigint,
  'name' : string,
  'specialty' : string,
  'contactNumber' : string,
}
export type ProfileSetupError = { 'NotFound' : null };
export interface ResponsiblePerson {
  'id' : bigint,
  'relationship' : string,
  'name' : string,
  'address' : string,
  'contactNumber' : string,
}
export type RoomType = { 'solo' : null } |
  { 'sharedRoom' : null };
export interface UserProfileWithRole {
  'name' : string,
  'role' : string,
  'employeeId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResidentAccessControl' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      string,
      RoomType,
      [] | [string],
      Array<Physician>,
      [] | [Pharmacy],
      [] | [Insurance],
      string,
      string,
      Array<ResponsiblePerson>,
      Array<Medication>,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'ensureRegisteredUser' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfileWithRole' : ActorMethod<
    [Principal],
    { 'ok' : UserProfileWithRole } |
      { 'err' : ProfileSetupError }
  >,
  'healthCheck' : ActorMethod<
    [],
    { 'message' : string, 'timestamp' : [] | [bigint] }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];