/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Medication {
    id: bigint;
    status: MedicationStatus;
    dosage: string;
    prescribingPhysician?: Physician;
    name: string;
    administrationRoute: AdministrationRoute;
    administrationTimes: Array<string>;
    notes: string;
    dosageQuantity: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Resident {
    id: bigint;
    bed?: string;
    status: ResidentStatus;
    weightLog: Array<WeightEntry>;
    dateOfBirth: bigint;
    admissionDate: bigint;
    marRecords: Array<MedicationAdministrationRecord>;
    adlRecords: Array<ADLRecord>;
    isArchived: boolean;
    roomNumber: string;
    insurance?: Insurance;
    medications: Array<Medication>;
    pharmacy?: Pharmacy;
    dailyVitals: Array<DailyVitals>;
    responsiblePersons: Array<ResponsiblePerson>;
    dischargeTimestamp?: bigint;
    medicaidNumber: string;
    physicians: Array<Physician>;
    lastName: string;
    roomType: RoomType;
    medicareNumber: string;
    firstName: string;
}
export interface Physician {
    id: bigint;
    name: string;
    specialty: string;
    contactNumber: string;
}
export interface ResponsiblePerson {
    id: bigint;
    relationship: string;
    name: string;
    address: string;
    contactNumber: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Insurance {
    id: bigint;
    address: string;
    companyName: string;
    contactNumber: string;
    policyNumber: string;
}
export interface ADLRecord {
    id: bigint;
    residentId: bigint;
    staffNotes: string;
    assistanceLevel: string;
    date: bigint;
    activity: string;
}
export interface UserProfileWithRole {
    name: string;
    role: string;
    employeeId: string;
}
export interface Pharmacy {
    id: bigint;
    name: string;
    address: string;
    contactNumber: string;
}
export interface DailyVitals {
    id: bigint;
    residentId: bigint;
    bloodGlucose?: bigint;
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    measurementDateTime: bigint;
    notes: string;
    bloodPressureDiastolic: bigint;
    bloodPressureSystolic: bigint;
}
export interface MedicationAdministrationRecord {
    id: bigint;
    medication: Medication;
    notes: string;
    administrationTime: bigint;
    administeredBy: string;
}
export interface WeightEntry {
    id: bigint;
    weight: number;
    residentId: bigint;
    weightUnit: string;
    notes: string;
    measurementDate: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    employeeId: string;
}
export enum AdministrationRoute {
    injection = "injection",
    inhaled = "inhaled",
    oral = "oral",
    intramuscular = "intramuscular",
    ophthalmic = "ophthalmic",
    transdermal = "transdermal",
    sublingual = "sublingual",
    intravenous = "intravenous",
    topical = "topical",
    subcutaneous = "subcutaneous",
    rectal = "rectal"
}
export enum MedicationStatus {
    active = "active",
    discontinued = "discontinued"
}
export enum ResidentStatus {
    active = "active",
    discharged = "discharged"
}
export enum RoomType {
    solo = "solo",
    sharedRoom = "sharedRoom"
}
export enum SortCriteria {
    bed = "bed",
    residentId = "residentId",
    name = "name",
    roomNumber = "roomNumber"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdlRecord(residentId: bigint, date: bigint, activity: string, assistanceLevel: string, staffNotes: string): Promise<void>;
    addDailyVitals(residentId: bigint, temperature: number, bloodPressureSystolic: bigint, bloodPressureDiastolic: bigint, pulseRate: bigint, respiratoryRate: bigint, oxygenSaturation: bigint, bloodGlucose: bigint | null, measurementDateTime: bigint, notes: string): Promise<void>;
    addInsurance(companyName: string, policyNumber: string, address: string, contactNumber: string): Promise<void>;
    addMarRecord(residentId: bigint, medication: Medication, administrationTime: bigint, administeredBy: string, notes: string): Promise<void>;
    addMedication(residentId: bigint, name: string, dosage: string, administrationTimes: Array<string>, prescribingPhysician: Physician | null, administrationRoute: AdministrationRoute, dosageQuantity: string, notes: string): Promise<void>;
    addPharmacy(name: string, address: string, contactNumber: string): Promise<void>;
    addPhysician(name: string, contactNumber: string, specialty: string): Promise<void>;
    addResident(firstName: string, lastName: string, dateOfBirth: bigint, admissionDate: bigint, roomNumber: string, roomType: RoomType, bed: string | null, physiciansData: Array<Physician>, pharmacyData: Pharmacy | null, insuranceData: Insurance | null, medicaidNumber: string, medicareNumber: string, responsiblePersonsData: Array<ResponsiblePerson>, medications: Array<Medication>): Promise<void>;
    addResponsiblePerson(name: string, relationship: string, contactNumber: string, address: string): Promise<void>;
    addWeightEntry(residentId: bigint, weight: number, weightUnit: string, measurementDate: bigint, notes: string): Promise<void>;
    archiveResident(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    autoArchiveDischargedResidents(): Promise<void>;
    calculateAge(_dateOfBirth: bigint): Promise<bigint>;
    checkUpgradeHealth(): Promise<{
        residents: bigint;
        nextResidentId: bigint;
        userProfiles: bigint;
    }>;
    dischargeResident(id: bigint): Promise<void>;
    editMedication(residentId: bigint, medicationId: bigint, name: string, dosage: string, administrationTimes: Array<string>, prescribingPhysician: Physician | null, administrationRoute: AdministrationRoute, dosageQuantity: string, notes: string): Promise<void>;
    findResidentByRoom(roomNumber: string): Promise<Resident | null>;
    generateAdlReport(residentId: bigint): Promise<Array<ADLRecord>>;
    generateFullMedicationReport(residentId: bigint): Promise<Array<Medication>>;
    generateMarReport(residentId: bigint): Promise<Array<MedicationAdministrationRecord>>;
    generateMedicationReport(residentId: bigint): Promise<Array<Medication>>;
    generateResidentProfileReport(residentId: bigint): Promise<Resident | null>;
    getActiveResidents(): Promise<Array<Resident>>;
    getAllInsuranceCompanies(): Promise<Array<Insurance>>;
    getAllPharmacies(): Promise<Array<Pharmacy>>;
    getAllPhysicians(): Promise<Array<Physician>>;
    getAllResidents(): Promise<Array<Resident>>;
    getAllResponsiblePersons(): Promise<Array<ResponsiblePerson>>;
    getAllRoomNumbers(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfileWithRole | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyVitals(residentId: bigint): Promise<Array<DailyVitals>>;
    getDischargedResidents(): Promise<Array<Resident>>;
    getFilteredAndSortedResidents(status: ResidentStatus | null, sortBy: SortCriteria | null): Promise<Array<Resident>>;
    getInsurance(id: bigint): Promise<Insurance | null>;
    getNonArchivedResidents(): Promise<Array<Resident>>;
    getPharmacy(id: bigint): Promise<Pharmacy | null>;
    getPhysician(id: bigint): Promise<Physician | null>;
    getResident(id: bigint): Promise<Resident | null>;
    getResidentCounts(): Promise<{
        activeResidents: bigint;
        archivedResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }>;
    getResidentRoomMap(): Promise<Array<[bigint, string]>>;
    getResidentStatistics(): Promise<{
        residentsByRoom: Array<[bigint, string, string]>;
        activeResidents: bigint;
        residentsByRoomType: Array<[bigint, string, RoomType]>;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }>;
    getResidentsByRoom(roomNumber: string): Promise<Array<Resident>>;
    getResidentsByRoomType(roomType: RoomType): Promise<Array<Resident>>;
    getResponsiblePerson(id: bigint): Promise<ResponsiblePerson | null>;
    getSystemDiagnostics(includeSample: boolean): Promise<{
        nextIdCounters: {
            nextPharmacyId: bigint;
            nextResponsiblePersonId: bigint;
            nextResidentId: bigint;
            nextPhysicianId: bigint;
            nextInsuranceId: bigint;
            nextMedicationId: bigint;
            nextWeightEntryId: bigint;
            nextMarId: bigint;
            nextAdlId: bigint;
            nextDailyVitalsId: bigint;
        };
        sampleData?: Array<[bigint, string]>;
        aggregateCounts: {
            activeResidents: bigint;
            archivedResidents: bigint;
            dischargedResidents: bigint;
            totalResidents: bigint;
        };
    }>;
    getUserProfile(user: Principal): Promise<UserProfileWithRole | null>;
    getWeightLog(residentId: bigint): Promise<Array<WeightEntry>>;
    healthCheck(): Promise<{
        message: string;
        timestamp?: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    permanentlyDeleteResident(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMedication(residentId: bigint, medicationId: bigint, name: string, dosage: string, administrationTimes: Array<string>, prescribingPhysician: Physician | null, administrationRoute: AdministrationRoute, dosageQuantity: string, notes: string, status: MedicationStatus): Promise<void>;
    updateMedicationStatus(residentId: bigint, medicationId: bigint, status: MedicationStatus): Promise<void>;
    updateResident(id: bigint, firstName: string, lastName: string, dateOfBirth: bigint, admissionDate: bigint, status: ResidentStatus, roomNumber: string, roomType: RoomType, bed: string | null, physicians: Array<Physician>, pharmacy: Pharmacy | null, insurance: Insurance | null, medicaidNumber: string, medicareNumber: string, responsiblePersons: Array<ResponsiblePerson>, medications: Array<Medication>): Promise<void>;
    v105_dischargeResident(id: bigint): Promise<void>;
    v105_permanentlyDeleteResident(id: bigint): Promise<void>;
}
import type { ADLRecord as _ADLRecord, AdministrationRoute as _AdministrationRoute, DailyVitals as _DailyVitals, Insurance as _Insurance, Medication as _Medication, MedicationAdministrationRecord as _MedicationAdministrationRecord, MedicationStatus as _MedicationStatus, Pharmacy as _Pharmacy, Physician as _Physician, Resident as _Resident, ResidentStatus as _ResidentStatus, ResponsiblePerson as _ResponsiblePerson, RoomType as _RoomType, SortCriteria as _SortCriteria, UserProfileWithRole as _UserProfileWithRole, UserRole as _UserRole, WeightEntry as _WeightEntry, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdlRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdlRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdlRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDailyVitals(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint | null, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyVitals(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyVitals(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return result;
        }
    }
    async addInsurance(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInsurance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInsurance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMarRecord(arg0: bigint, arg1: Medication, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarRecord(arg0, to_candid_Medication_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarRecord(arg0, to_candid_Medication_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async addMedication(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: Physician | null, arg5: AdministrationRoute, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async addPharmacy(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPharmacy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPharmacy(arg0, arg1, arg2);
            return result;
        }
    }
    async addPhysician(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhysician(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhysician(arg0, arg1, arg2);
            return result;
        }
    }
    async addResident(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: RoomType, arg6: string | null, arg7: Array<Physician>, arg8: Pharmacy | null, arg9: Insurance | null, arg10: string, arg11: string, arg12: Array<ResponsiblePerson>, arg13: Array<Medication>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResident(arg0, arg1, arg2, arg3, arg4, to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResident(arg0, arg1, arg2, arg3, arg4, to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async addResponsiblePerson(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResponsiblePerson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResponsiblePerson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addWeightEntry(arg0: bigint, arg1: number, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async archiveResident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveResident(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoArchiveDischargedResidents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.autoArchiveDischargedResidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoArchiveDischargedResidents();
            return result;
        }
    }
    async calculateAge(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAge(arg0);
            return result;
        }
    }
    async checkUpgradeHealth(): Promise<{
        residents: bigint;
        nextResidentId: bigint;
        userProfiles: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUpgradeHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUpgradeHealth();
            return result;
        }
    }
    async dischargeResident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dischargeResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dischargeResident(arg0);
            return result;
        }
    }
    async editMedication(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Array<string>, arg5: Physician | null, arg6: AdministrationRoute, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async findResidentByRoom(arg0: string): Promise<Resident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findResidentByRoom(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findResidentByRoom(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateAdlReport(arg0: bigint): Promise<Array<ADLRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAdlReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAdlReport(arg0);
            return result;
        }
    }
    async generateFullMedicationReport(arg0: bigint): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFullMedicationReport(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFullMedicationReport(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateMarReport(arg0: bigint): Promise<Array<MedicationAdministrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMarReport(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMarReport(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateMedicationReport(arg0: bigint): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMedicationReport(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMedicationReport(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateResidentProfileReport(arg0: bigint): Promise<Resident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateResidentProfileReport(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateResidentProfileReport(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveResidents();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveResidents();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInsuranceCompanies(): Promise<Array<Insurance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInsuranceCompanies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInsuranceCompanies();
            return result;
        }
    }
    async getAllPharmacies(): Promise<Array<Pharmacy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPharmacies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPharmacies();
            return result;
        }
    }
    async getAllPhysicians(): Promise<Array<Physician>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhysicians();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhysicians();
            return result;
        }
    }
    async getAllResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResidents();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResidents();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResponsiblePersons(): Promise<Array<ResponsiblePerson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResponsiblePersons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResponsiblePersons();
            return result;
        }
    }
    async getAllRoomNumbers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomNumbers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileWithRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyVitals(arg0: bigint): Promise<Array<DailyVitals>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyVitals(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyVitals(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDischargedResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDischargedResidents();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDischargedResidents();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredAndSortedResidents(arg0: ResidentStatus | null, arg1: SortCriteria | null): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredAndSortedResidents(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredAndSortedResidents(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsurance(arg0: bigint): Promise<Insurance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsurance(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsurance(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNonArchivedResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNonArchivedResidents();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNonArchivedResidents();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPharmacy(arg0: bigint): Promise<Pharmacy | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacy(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacy(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhysician(arg0: bigint): Promise<Physician | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhysician(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhysician(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResident(arg0: bigint): Promise<Resident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResident(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResident(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentCounts(): Promise<{
        activeResidents: bigint;
        archivedResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentCounts();
            return result;
        }
    }
    async getResidentRoomMap(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentRoomMap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentRoomMap();
            return result;
        }
    }
    async getResidentStatistics(): Promise<{
        residentsByRoom: Array<[bigint, string, string]>;
        activeResidents: bigint;
        residentsByRoomType: Array<[bigint, string, RoomType]>;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentStatistics();
                return from_candid_record_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentStatistics();
            return from_candid_record_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentsByRoom(arg0: string): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentsByRoom(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentsByRoom(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentsByRoomType(arg0: RoomType): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentsByRoomType(to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentsByRoomType(to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsiblePerson(arg0: bigint): Promise<ResponsiblePerson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsiblePerson(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsiblePerson(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemDiagnostics(arg0: boolean): Promise<{
        nextIdCounters: {
            nextPharmacyId: bigint;
            nextResponsiblePersonId: bigint;
            nextResidentId: bigint;
            nextPhysicianId: bigint;
            nextInsuranceId: bigint;
            nextMedicationId: bigint;
            nextWeightEntryId: bigint;
            nextMarId: bigint;
            nextAdlId: bigint;
            nextDailyVitalsId: bigint;
        };
        sampleData?: Array<[bigint, string]>;
        aggregateCounts: {
            activeResidents: bigint;
            archivedResidents: bigint;
            dischargedResidents: bigint;
            totalResidents: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemDiagnostics(arg0);
                return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemDiagnostics(arg0);
            return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileWithRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightLog(arg0: bigint): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightLog(arg0);
            return result;
        }
    }
    async healthCheck(): Promise<{
        message: string;
        timestamp?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return from_candid_record_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return from_candid_record_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async permanentlyDeleteResident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentlyDeleteResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentlyDeleteResident(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateMedication(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Array<string>, arg5: Physician | null, arg6: AdministrationRoute, arg7: string, arg8: string, arg9: MedicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_MedicationStatus_n11(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_AdministrationRoute_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_MedicationStatus_n11(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async updateMedicationStatus(arg0: bigint, arg1: bigint, arg2: MedicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicationStatus(arg0, arg1, to_candid_MedicationStatus_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicationStatus(arg0, arg1, to_candid_MedicationStatus_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateResident(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: ResidentStatus, arg6: string, arg7: RoomType, arg8: string | null, arg9: Array<Physician>, arg10: Pharmacy | null, arg11: Insurance | null, arg12: string, arg13: string, arg14: Array<ResponsiblePerson>, arg15: Array<Medication>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResident(arg0, arg1, arg2, arg3, arg4, to_candid_ResidentStatus_n54(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg15));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResident(arg0, arg1, arg2, arg3, arg4, to_candid_ResidentStatus_n54(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_RoomType_n16(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg15));
            return result;
        }
    }
    async v105_dischargeResident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.v105_dischargeResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.v105_dischargeResident(arg0);
            return result;
        }
    }
    async v105_permanentlyDeleteResident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.v105_permanentlyDeleteResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.v105_permanentlyDeleteResident(arg0);
            return result;
        }
    }
}
function from_candid_AdministrationRoute_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdministrationRoute): AdministrationRoute {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_DailyVitals_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyVitals): DailyVitals {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_MedicationAdministrationRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicationAdministrationRecord): MedicationAdministrationRecord {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MedicationStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicationStatus): MedicationStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Medication_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medication): Medication {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ResidentStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentStatus): ResidentStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Resident_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resident): Resident {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resident]): Resident | null {
    return value.length === 0 ? null : from_candid_Resident_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Physician]): Physician | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Insurance]): Insurance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pharmacy]): Pharmacy | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileWithRole]): UserProfileWithRole | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResponsiblePerson]): ResponsiblePerson | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[bigint, string]>]): Array<[bigint, string]> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bed: [] | [string];
    status: _ResidentStatus;
    weightLog: Array<_WeightEntry>;
    dateOfBirth: bigint;
    admissionDate: bigint;
    marRecords: Array<_MedicationAdministrationRecord>;
    adlRecords: Array<_ADLRecord>;
    isArchived: boolean;
    roomNumber: string;
    insurance: [] | [_Insurance];
    medications: Array<_Medication>;
    pharmacy: [] | [_Pharmacy];
    dailyVitals: Array<_DailyVitals>;
    responsiblePersons: Array<_ResponsiblePerson>;
    dischargeTimestamp: [] | [bigint];
    medicaidNumber: string;
    physicians: Array<_Physician>;
    lastName: string;
    roomType: _RoomType;
    medicareNumber: string;
    firstName: string;
}): {
    id: bigint;
    bed?: string;
    status: ResidentStatus;
    weightLog: Array<WeightEntry>;
    dateOfBirth: bigint;
    admissionDate: bigint;
    marRecords: Array<MedicationAdministrationRecord>;
    adlRecords: Array<ADLRecord>;
    isArchived: boolean;
    roomNumber: string;
    insurance?: Insurance;
    medications: Array<Medication>;
    pharmacy?: Pharmacy;
    dailyVitals: Array<DailyVitals>;
    responsiblePersons: Array<ResponsiblePerson>;
    dischargeTimestamp?: bigint;
    medicaidNumber: string;
    physicians: Array<Physician>;
    lastName: string;
    roomType: RoomType;
    medicareNumber: string;
    firstName: string;
} {
    return {
        id: value.id,
        bed: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.bed)),
        status: from_candid_ResidentStatus_n28(_uploadFile, _downloadFile, value.status),
        weightLog: value.weightLog,
        dateOfBirth: value.dateOfBirth,
        admissionDate: value.admissionDate,
        marRecords: from_candid_vec_n30(_uploadFile, _downloadFile, value.marRecords),
        adlRecords: value.adlRecords,
        isArchived: value.isArchived,
        roomNumber: value.roomNumber,
        insurance: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.insurance)),
        medications: from_candid_vec_n41(_uploadFile, _downloadFile, value.medications),
        pharmacy: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.pharmacy)),
        dailyVitals: from_candid_vec_n43(_uploadFile, _downloadFile, value.dailyVitals),
        responsiblePersons: value.responsiblePersons,
        dischargeTimestamp: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.dischargeTimestamp)),
        medicaidNumber: value.medicaidNumber,
        physicians: value.physicians,
        lastName: value.lastName,
        roomType: from_candid_RoomType_n47(_uploadFile, _downloadFile, value.roomType),
        medicareNumber: value.medicareNumber,
        firstName: value.firstName
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    medication: _Medication;
    notes: string;
    administrationTime: bigint;
    administeredBy: string;
}): {
    id: bigint;
    medication: Medication;
    notes: string;
    administrationTime: bigint;
    administeredBy: string;
} {
    return {
        id: value.id,
        medication: from_candid_Medication_n33(_uploadFile, _downloadFile, value.medication),
        notes: value.notes,
        administrationTime: value.administrationTime,
        administeredBy: value.administeredBy
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MedicationStatus;
    dosage: string;
    prescribingPhysician: [] | [_Physician];
    name: string;
    administrationRoute: _AdministrationRoute;
    administrationTimes: Array<string>;
    notes: string;
    dosageQuantity: string;
}): {
    id: bigint;
    status: MedicationStatus;
    dosage: string;
    prescribingPhysician?: Physician;
    name: string;
    administrationRoute: AdministrationRoute;
    administrationTimes: Array<string>;
    notes: string;
    dosageQuantity: string;
} {
    return {
        id: value.id,
        status: from_candid_MedicationStatus_n35(_uploadFile, _downloadFile, value.status),
        dosage: value.dosage,
        prescribingPhysician: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.prescribingPhysician)),
        name: value.name,
        administrationRoute: from_candid_AdministrationRoute_n38(_uploadFile, _downloadFile, value.administrationRoute),
        administrationTimes: value.administrationTimes,
        notes: value.notes,
        dosageQuantity: value.dosageQuantity
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    residentId: bigint;
    bloodGlucose: [] | [bigint];
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    measurementDateTime: bigint;
    notes: string;
    bloodPressureDiastolic: bigint;
    bloodPressureSystolic: bigint;
}): {
    id: bigint;
    residentId: bigint;
    bloodGlucose?: bigint;
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    measurementDateTime: bigint;
    notes: string;
    bloodPressureDiastolic: bigint;
    bloodPressureSystolic: bigint;
} {
    return {
        id: value.id,
        residentId: value.residentId,
        bloodGlucose: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bloodGlucose)),
        respiratoryRate: value.respiratoryRate,
        temperature: value.temperature,
        pulseRate: value.pulseRate,
        oxygenSaturation: value.oxygenSaturation,
        measurementDateTime: value.measurementDateTime,
        notes: value.notes,
        bloodPressureDiastolic: value.bloodPressureDiastolic,
        bloodPressureSystolic: value.bloodPressureSystolic
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    residentsByRoom: Array<[bigint, string, string]>;
    activeResidents: bigint;
    residentsByRoomType: Array<[bigint, string, _RoomType]>;
    dischargedResidents: bigint;
    totalResidents: bigint;
}): {
    residentsByRoom: Array<[bigint, string, string]>;
    activeResidents: bigint;
    residentsByRoomType: Array<[bigint, string, RoomType]>;
    dischargedResidents: bigint;
    totalResidents: bigint;
} {
    return {
        residentsByRoom: value.residentsByRoom,
        activeResidents: value.activeResidents,
        residentsByRoomType: from_candid_vec_n60(_uploadFile, _downloadFile, value.residentsByRoomType),
        dischargedResidents: value.dischargedResidents,
        totalResidents: value.totalResidents
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextIdCounters: {
        nextPharmacyId: bigint;
        nextResponsiblePersonId: bigint;
        nextResidentId: bigint;
        nextPhysicianId: bigint;
        nextInsuranceId: bigint;
        nextMedicationId: bigint;
        nextWeightEntryId: bigint;
        nextMarId: bigint;
        nextAdlId: bigint;
        nextDailyVitalsId: bigint;
    };
    sampleData: [] | [Array<[bigint, string]>];
    aggregateCounts: {
        activeResidents: bigint;
        archivedResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    };
}): {
    nextIdCounters: {
        nextPharmacyId: bigint;
        nextResponsiblePersonId: bigint;
        nextResidentId: bigint;
        nextPhysicianId: bigint;
        nextInsuranceId: bigint;
        nextMedicationId: bigint;
        nextWeightEntryId: bigint;
        nextMarId: bigint;
        nextAdlId: bigint;
        nextDailyVitalsId: bigint;
    };
    sampleData?: Array<[bigint, string]>;
    aggregateCounts: {
        activeResidents: bigint;
        archivedResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    };
} {
    return {
        nextIdCounters: value.nextIdCounters,
        sampleData: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.sampleData)),
        aggregateCounts: value.aggregateCounts
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    timestamp: [] | [bigint];
}): {
    message: string;
    timestamp?: bigint;
} {
    return {
        message: value.message,
        timestamp: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.timestamp))
    };
}
function from_candid_tuple_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, string, _RoomType]): [bigint, string, RoomType] {
    return [
        value[0],
        value[1],
        from_candid_RoomType_n47(_uploadFile, _downloadFile, value[2])
    ];
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    discharged: null;
}): ResidentStatus {
    return "active" in value ? ResidentStatus.active : "discharged" in value ? ResidentStatus.discharged : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    discontinued: null;
}): MedicationStatus {
    return "active" in value ? MedicationStatus.active : "discontinued" in value ? MedicationStatus.discontinued : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    injection: null;
} | {
    inhaled: null;
} | {
    oral: null;
} | {
    intramuscular: null;
} | {
    ophthalmic: null;
} | {
    transdermal: null;
} | {
    sublingual: null;
} | {
    intravenous: null;
} | {
    topical: null;
} | {
    subcutaneous: null;
} | {
    rectal: null;
}): AdministrationRoute {
    return "injection" in value ? AdministrationRoute.injection : "inhaled" in value ? AdministrationRoute.inhaled : "oral" in value ? AdministrationRoute.oral : "intramuscular" in value ? AdministrationRoute.intramuscular : "ophthalmic" in value ? AdministrationRoute.ophthalmic : "transdermal" in value ? AdministrationRoute.transdermal : "sublingual" in value ? AdministrationRoute.sublingual : "intravenous" in value ? AdministrationRoute.intravenous : "topical" in value ? AdministrationRoute.topical : "subcutaneous" in value ? AdministrationRoute.subcutaneous : "rectal" in value ? AdministrationRoute.rectal : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solo: null;
} | {
    sharedRoom: null;
}): RoomType {
    return "solo" in value ? RoomType.solo : "sharedRoom" in value ? RoomType.sharedRoom : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicationAdministrationRecord>): Array<MedicationAdministrationRecord> {
    return value.map((x)=>from_candid_MedicationAdministrationRecord_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medication>): Array<Medication> {
    return value.map((x)=>from_candid_Medication_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyVitals>): Array<DailyVitals> {
    return value.map((x)=>from_candid_DailyVitals_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resident>): Array<Resident> {
    return value.map((x)=>from_candid_Resident_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, string, _RoomType]>): Array<[bigint, string, RoomType]> {
    return value.map((x)=>from_candid_tuple_n61(_uploadFile, _downloadFile, x));
}
function to_candid_AdministrationRoute_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdministrationRoute): _AdministrationRoute {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_MedicationStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicationStatus): _MedicationStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Medication_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medication): _Medication {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ResidentStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus): _ResidentStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SortCriteria_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortCriteria): _SortCriteria {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Physician | null): [] | [_Physician] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pharmacy | null): [] | [_Pharmacy] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Insurance | null): [] | [_Insurance] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus | null): [] | [_ResidentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ResidentStatus_n54(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortCriteria | null): [] | [_SortCriteria] {
    return value === null ? candid_none() : candid_some(to_candid_SortCriteria_n57(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: MedicationStatus;
    dosage: string;
    prescribingPhysician?: Physician;
    name: string;
    administrationRoute: AdministrationRoute;
    administrationTimes: Array<string>;
    notes: string;
    dosageQuantity: string;
}): {
    id: bigint;
    status: _MedicationStatus;
    dosage: string;
    prescribingPhysician: [] | [_Physician];
    name: string;
    administrationRoute: _AdministrationRoute;
    administrationTimes: Array<string>;
    notes: string;
    dosageQuantity: string;
} {
    return {
        id: value.id,
        status: to_candid_MedicationStatus_n11(_uploadFile, _downloadFile, value.status),
        dosage: value.dosage,
        prescribingPhysician: value.prescribingPhysician ? candid_some(value.prescribingPhysician) : candid_none(),
        name: value.name,
        administrationRoute: to_candid_AdministrationRoute_n13(_uploadFile, _downloadFile, value.administrationRoute),
        administrationTimes: value.administrationTimes,
        notes: value.notes,
        dosageQuantity: value.dosageQuantity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicationStatus): {
    active: null;
} | {
    discontinued: null;
} {
    return value == MedicationStatus.active ? {
        active: null
    } : value == MedicationStatus.discontinued ? {
        discontinued: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdministrationRoute): {
    injection: null;
} | {
    inhaled: null;
} | {
    oral: null;
} | {
    intramuscular: null;
} | {
    ophthalmic: null;
} | {
    transdermal: null;
} | {
    sublingual: null;
} | {
    intravenous: null;
} | {
    topical: null;
} | {
    subcutaneous: null;
} | {
    rectal: null;
} {
    return value == AdministrationRoute.injection ? {
        injection: null
    } : value == AdministrationRoute.inhaled ? {
        inhaled: null
    } : value == AdministrationRoute.oral ? {
        oral: null
    } : value == AdministrationRoute.intramuscular ? {
        intramuscular: null
    } : value == AdministrationRoute.ophthalmic ? {
        ophthalmic: null
    } : value == AdministrationRoute.transdermal ? {
        transdermal: null
    } : value == AdministrationRoute.sublingual ? {
        sublingual: null
    } : value == AdministrationRoute.intravenous ? {
        intravenous: null
    } : value == AdministrationRoute.topical ? {
        topical: null
    } : value == AdministrationRoute.subcutaneous ? {
        subcutaneous: null
    } : value == AdministrationRoute.rectal ? {
        rectal: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    solo: null;
} | {
    sharedRoom: null;
} {
    return value == RoomType.solo ? {
        solo: null
    } : value == RoomType.sharedRoom ? {
        sharedRoom: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus): {
    active: null;
} | {
    discharged: null;
} {
    return value == ResidentStatus.active ? {
        active: null
    } : value == ResidentStatus.discharged ? {
        discharged: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortCriteria): {
    bed: null;
} | {
    residentId: null;
} | {
    name: null;
} | {
    roomNumber: null;
} {
    return value == SortCriteria.bed ? {
        bed: null
    } : value == SortCriteria.residentId ? {
        residentId: null
    } : value == SortCriteria.name ? {
        name: null
    } : value == SortCriteria.roomNumber ? {
        roomNumber: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Medication>): Array<_Medication> {
    return value.map((x)=>to_candid_Medication_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
